### ISSUE TITLE
Database Changes

### ISSUE THREAD

**Issue by BLamy** [mxs4321/WASPS-Scheduling-System#49]
@lzganec What do you think about doing these changes? 

- [x] `comments` table renamed to `comment`
- [x] `driveravailability` table renamed to `availability`
- [x] `driveravailabilityexception` table renamed to `availabilityblacklist`
- [x] `sentmessageslog` table should be renamed to `notifications`
- [x] `wantsEmails`in User table should just be `wantsEmail`
- [x] `userRole` in User table should just be `role`
- [x] `userID` in rides should probably be `passangerID`

**Comment by lzganec** [comment]
Sounds good. Might change the blacklist into something a bit softer like exclusion/omission, blacklist just gives wrong impression about its purpose. Otherwise a fair change to make it simpler.
