### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by BLamy** [mxs4321/WASPS-Scheduling-System#90]
### All

- [x] All PUT, and DELETE endpoints should take the ID of the user getting updated or deleted as a GET argument
- [x] All POST, and PUT endpoints should return the record that was updated or deleted. (Query the database afterward, pull the new record out and return as json).

### /api/users.php
**GET**
- [x] For some reason Get by ID doesn't seem to be working anymore.
- [x] For some reason Get by Name doesn't seem to be working anymore.

**PUT**

- [x] Admins should be able to create admins
- [x] Admins should be able to create dispatchers
- [x] Admins should be able to create Drivers
- [x] When you create a user you should send return the newly created user

**POST**

- [x] You should take the user id to update in as a GET param. 
- [x] You should also return the newly updated user as a json object. 

## /api/driverAvilabilities.php

**GET**

- [x] DriverAvilability doesn't seem to work right. The main driver should be Avilabile to drive on a monday at 10am

**Comment by lzganec** [comment]
Just so we don't forget: DriverAvailability didn't work since the dummy data has endTime < startTime. Need to validate the data entry.
